Update openocd_gdb_debugging.md
Running the original command in Mac terminal:

`brew tap PX4/homebrew-px`

will result in the following error:

`==> Tapping px4/px
Cloning into '/opt/homebrew/Library/Taps/px4/homebrew-px'...
remote: Repository not found.
fatal: repository 'https://github.com/PX4/homebrew-px/' not found
Error: Failure while executing; `git clone https://github.com/PX4/homebrew-px /opt/homebrew/Library/Taps/px4/homebrew-px --origin=origin --template= --config core.fsmonitor=false` exited with 128.`

It turns out that the correct GitHub repo for the brew formula is the following:

`https://github.com/PX4/homebrew-px4`